### ISSUE TITLE
Crash on resuming call screen on other device

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#111]
1. Call device B from device A.
2. End the call from either device.
3. On device B, the Recent Apps carousel shows the call screen.
4. Tap on it to open.

Crash log:

```
FATAL EXCEPTION: main
Process: d.d.meshenger, PID: 27012
java.lang.NullPointerException
	at d.d.meshenger.CallActivity$initIncomingCall$1.onServiceConnected(CallActivity.kt:574)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I think the expected behaviour would be to open the app's main screen.

**Comment by mwarning** [comment]
When I end the call in step 2, then the App returns to the main screen. And the main screen is what I see in the list of Recent Apps. Do I miss something?

I can fix the null pointer exception, but it would be nice to verify the bugfix.

**Comment by mwarning** [comment]
Just to be sure, this is the Recent Apps you refer to? https://developer.android.com/guide/components/activities/recents

**Comment by mwarning** [comment]
OK, I can reproduce the error this way. Let' see.

**Comment by mwarning** [comment]
This should fix it: https://github.com/meshenger-app/meshenger-android/commits/master
