### ISSUE TITLE
3.0.0 todo list

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#18]
- <strike>fix exceptions when adding existing contacts via qr code</strike>
- <strike>add database password salt</strike>
  - <strike>also add upgrade of database encryption</strike> => not applicable. contact keys are not compatible anyway :/
- <strike>add contact name change form if contact with existing name is scanned</strike>
- outgoing call from call history gets interrupted (sometimes)
- <strike>add missed calls</strike>
- <strike>show call times</strike>
- <strike>show if call was missed etc.</strike>
- <strike>show call sender IP address?</strike>
- <strike>sort calls by date</strike>
- <strike>allow to enable wifi or skip on first startup</strike>
- <strike >warn when add not existing IP/MAC addresses (not domains)</strike>
- <strike>set last successful IP address</strike>
- <strike>proper address entry when adding unknown callers (extract MAC from EUI-64)?</strike>
- <strike>update screenshots</strike>
- <strike>fix AddressActivity.parseAddress</strike>
- <strike>rename all dialog xml files to start with dialog_ in the file name</strike>
- <strike>set ice servers if set / give better description</strike>
  - <strike>set them for WebRTC</strike>
- <strike>fix calls</strike>
- use socket sender address of same scope&scheme as own address if possible. This makes adding an address for an unknown caller much easier, android does not seem to do that...

**Comment by mwarning** [comment]
Something that needs to be fixed:
```
2019-09-19 02:24:17.945 12680-12680/d.d.meshenger I/FloatingActionButton: Setting a custom background is not supported.
2019-09-19 02:24:17.949 12680-12680/d.d.meshenger D/ContactListFragment: refreshContactList
2019-09-19 02:24:17.949 12680-12680/d.d.meshenger D/ContactListFragment: onResume
2019-09-19 02:24:17.952 12680-12680/d.d.meshenger I/FloatingActionButton: Setting a custom background is not supported.
2019-09-19 02:24:17.956 12680-12680/d.d.meshenger D/EventListFragment: onResume
2019-09-19 02:24:17.961 12680-12680/d.d.meshenger D/ContactListFragment: setActivity
2019-09-19 02:24:17.961 12680-12680/d.d.meshenger D/EventListFragment: refreshEventList
2019-09-19 02:24:17.976 12680-12685/d.d.meshenger I/art: Do partial code cache collection, code=44KB, data=62KB
2019-09-19 02:24:17.977 12680-12685/d.d.meshenger I/art: After code cache collection, code=44KB, data=62KB
2019-09-19 02:24:17.978 12680-12685/d.d.meshenger I/art: Increasing code cache capacity to 256KB
2019-09-19 02:24:17.984 12680-12680/d.d.meshenger D/EventListFragment: refreshEventList update: 3
2019-09-19 02:24:18.248 12680-12680/d.d.meshenger D/CallActivity: onDestroy
2019-09-19 02:24:18.248 12680-12680/d.d.meshenger D/CallActivity: stopRinging
2019-09-19 02:24:18.248 12680-12680/d.d.meshenger D/RTCCall: closeCommSocket
2019-09-19 02:24:18.251 12680-12680/d.d.meshenger I/org.webrtc.Logging: CameraCapturer: Stop capture
2019-09-19 02:24:18.251 12680-12680/d.d.meshenger I/org.webrtc.Logging: CameraCapturer: Stop capture: No session open
2019-09-19 02:24:18.251 12680-12680/d.d.meshenger I/org.webrtc.Logging: CameraCapturer: Stop capture done
2019-09-19 02:24:18.251 12680-12680/d.d.meshenger I/org.webrtc.Logging: EglRenderer: remoteRendererReleasing.
2019-09-19 02:24:18.251 12680-12680/d.d.meshenger I/org.webrtc.Logging: EglRenderer: remoteRendererAlready released
2019-09-19 02:24:18.263 12680-12680/d.d.meshenger E/ActivityThread: Activity d.d.meshenger.CallActivity has leaked IntentReceiver org.webrtc.NetworkMonitorAutoDetect@8fc1c3 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity d.d.meshenger.CallActivity has leaked IntentReceiver org.webrtc.NetworkMonitorAutoDetect@8fc1c3 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
        at org.webrtc.NetworkMonitorAutoDetect.registerReceiver(NetworkMonitorAutoDetect.java:735)
        at org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:653)
        at org.webrtc.NetworkMonitor.createAutoDetect(NetworkMonitor.java:169)
        at org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:92)
        at org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:114)
2019-09-19 02:24:48.725 12680-12680/d.d.meshenger D/MainActivity: onPause
```

**Comment by mwarning** [comment]
Let's make a release for now.
