### ISSUE TITLE
crash: "Unable to find any matching EGL config"

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#2]
The crash happens when the Android 5 phone accepts the call (either receiving or initiating).
```
07-11 22:32:55.075 1966-4136/? D/audio_hw_primary: select_input_device: AUDIO_DEVICE_IN_BUILTIN_MIC
07-11 22:32:55.075 4053-4116/d.d.meshenger I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW video decoder for codec VP8
07-11 22:32:55.080 4053-4116/d.d.meshenger I/org.webrtc.Logging: MediaCodecVideoDecoder: No HW video decoder for codec VP9
07-11 22:32:55.090 4053-4137/d.d.meshenger I/org.webrtc.Logging: WebRtcAudioRecord: AudioRecordThread@[name=AudioRecordJavaThread, id=210]
07-11 22:32:55.095 4053-4138/d.d.meshenger I/org.webrtc.Logging: MediaCodecVideoEncoder: No HW video encoder for codec VP8
07-11 22:32:55.115 4053-4117/d.d.meshenger D/RTCCall: change CHECKING
07-11 22:32:55.125 4053-4117/d.d.meshenger D/RTCCall: handling video stream
07-11 22:32:55.125 4053-4053/d.d.meshenger I/org.webrtc.Logging: EglRenderer: remoteRendererInitializing EglRenderer
07-11 22:32:55.130 4053-4117/d.d.meshenger D/RTCCall: change CONNECTED
07-11 22:32:55.130 4053-4117/d.d.meshenger D/RTCCall: change COMPLETED
07-11 22:32:55.130 4053-4143/d.d.meshenger I/org.webrtc.Logging: EglRenderer: remoteRendererEglBase10.create context
07-11 22:32:55.135 4053-4117/d.d.meshenger D/RTCCall: success
07-11 22:32:55.135 4053-4053/d.d.meshenger D/AndroidRuntime: Shutting down VM
07-11 22:32:55.145 4053-4053/d.d.meshenger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: d.d.meshenger, PID: 4053
    Theme: themes:{}
    java.lang.RuntimeException: java.lang.RuntimeException: Unable to find any matching EGL config
        at org.webrtc.EglBase10.getEglConfig(EglBase10.java:297)
        at org.webrtc.EglBase10.<init>(EglBase10.java:61)
        at org.webrtc.EglBase$$CC.createEgl10$$STATIC$$(Unknown Source)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:187)
        at org.webrtc.EglRenderer$$Lambda$0.run(Unknown Source)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:181)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at d.d.meshenger.RTCCall.lambda$handleMediaStream$2$RTCCall(RTCCall.java:290)
        at d.d.meshenger.RTCCall$$Lambda$2.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.RuntimeException: Unable to find any matching EGL config
        at org.webrtc.EglBase10.getEglConfig(EglBase10.java:297)
        at org.webrtc.EglBase10.<init>(EglBase10.java:61)
        at org.webrtc.EglBase$$CC.createEgl10$$STATIC$$(Unknown Source)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:187)
        at org.webrtc.EglRenderer$$Lambda$0.run(Unknown Source)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mwarning** [comment]
@dakhnod do you have an idea?

**Comment by mwarning** [comment]
Another stack trace:
```
07-11 22:40:26.620 4174-4226/d.d.meshenger E/org.webrtc.Logging: SurfaceTextureHelper: VideoCapturerThread create failure
07-11 22:40:26.635 4174-4226/d.d.meshenger E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Unable to find any matching EGL config
07-11 22:40:26.645 4174-4226/d.d.meshenger E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Unable to find any matching EGL config
        at org.webrtc.EglBase14.getEglConfig(EglBase14.java:250)
        at org.webrtc.EglBase14.<init>(EglBase14.java:70)
        at org.webrtc.EglBase$$CC.create$$STATIC$$(Unknown Source)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:119)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:34)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:68)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:63)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mwarning** [comment]
Closing for now. The code has changed. Maybe the error is gone.
