### ISSUE TITLE
crash miui 10.3

### ISSUE THREAD

**Issue by userkilled** [meshenger-app/meshenger-android#26]
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList d.d.meshenger.Database.contacts' on a null object reference
	at d.d.meshenger.MainService$MainBinder.getContactsCopy(MainService.java:394)
	at d.d.meshenger.MainService$MainBinder.pingContacts(MainService.java:378)
	at d.d.meshenger.MainActivity.onServiceConnected(MainActivity.java:86)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1670)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1699)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by mwarning** [comment]
This seems to be the same issue as #16. Thanks for the update.

I have added a debug build to the release. It should have more debug messages:
https://github.com/meshenger-app/meshenger-android/releases/download/v3.0.3/meshenger-3.0.3-debug.apk

**Comment by mwarning** [comment]
This error happens when you minimize the app?

**Comment by userkilled** [comment]
Yes.

**Comment by mwarning** [comment]
I think I also got this kind of error. But it is hard to replicate for me.

**Comment by userkilled** [comment]
![Screenshot_2019-10-26-11-52-11-903_com google android packageinstaller](https://user-images.githubusercontent.com/39238592/67616981-434aea80-f7e7-11e9-8e8d-c39e01558929.png)
Not install

**Comment by mwarning** [comment]
i have never seen this problem. What does the message say?

**Comment by userkilled** [comment]
failed to install the application.

**Comment by adicoder95** [comment]
This was because the app wasn't compatible with higher android versions.
But its fixed now, in the GSOC-22 branch.
