### ISSUE TITLE
Null Pointer Exception : On clicking on any contact to call

### ISSUE THREAD

**Issue by tusharbaweja264** [meshenger-app/meshenger-android#51]
2021-01-20 17:14:28.437 29745-29745/d.d.meshenger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: d.d.meshenger, PID: 29745
    java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList d.d.meshenger.Database.contacts' on a null object reference
        at d.d.meshenger.MainService$MainBinder.getContactsCopy(MainService.java:479)
        at d.d.meshenger.MainService$MainBinder.pingContacts(MainService.java:463)
        at d.d.meshenger.MainActivity.onServiceConnected(MainActivity.java:115)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1758)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1790)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6880)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mwarning** [comment]
This should fix it: https://github.com/meshenger-app/meshenger-android/commit/48785fdcfdcbba8c5f18f1759ece865aaa28ccca

**Comment by tusharbaweja264** [comment]
> This should fix it: [48785fd](https://github.com/meshenger-app/meshenger-android/commit/48785fdcfdcbba8c5f18f1759ece865aaa28ccca)

This fix doesn't work on this issue. Its related to contact fields as mentioned in the crash details "java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList d.d.meshenger.Database.contacts' on a null object reference"

**Comment by mwarning** [comment]
Ah, right. I will have a look later this week.

**Comment by tusharbaweja264** [comment]
Hey mwarning, Is there any update on this bug?

**Comment by tusharbaweja264** [comment]
Hey mwarning, Is there any update on this bug?

**Comment by mwarning** [comment]
Sort of, I am in the process of a refactoring and will address it as part of it.

**Comment by tusharbaweja264** [comment]
> Sort of, I am in the process of a refactoring and will address it as part of it.

Actually I am stuck due to this particular issue. I'd really appreciate if get any result soon.

**Comment by mwarning** [comment]
I see. I will have something working in about a week or two.

**Comment by tusharbaweja264** [comment]
Any update on this issue?

**Comment by mwarning** [comment]
I have added hot fix to master, since the refactoring takes more time then expected.
But I was not able to reproduce the error. That is why I cannot guarantee that this bug is fixed.

**Comment by mwarning** [comment]
The new code might still have the issue. But let's start new.
