### ISSUE TITLE
Calling on Android 8 broken

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#97]
This is also a pre-release bug I've mentioned before. The app can't be used with Android 8, but the situation seems to be improving with newer releases.

At the beginning, even placing a call caused a crash or error of some kind. As of 4.1.1, the Android 8 device can connect to another on a call, but there is no audio or video. Eventually, there is a crash on the _other_ device.

Log of that crash:

```
FATAL EXCEPTION: main
Process: d.d.meshenger, PID: 3826
java.lang.NullPointerException
	at d.d.meshenger.CallActivity$initIncomingCall$1.onServiceConnected(CallActivity.kt:497)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by mwarning** [comment]
This is odd. I have run a few tests with Android 8.

**Comment by mwarning** [comment]
@opusforlife2
* How often does this crash occur? Like every time?
* Can you provide me the log output while using a debug build (see https://github.com/meshenger-app/meshenger-android/releases/tag/v4.1.1 `meshenger-4.1.1_debug.apk`). This would help to understand why this is happening.

**Comment by mwarning** [comment]
On the Android 8 device is fine.

**Comment by mwarning** [comment]
Maybe you need android-studio like I use. But there are probably alternative ways to get this so called "logcat" outout.

**Comment by mwarning** [comment]
You should have at least the data visible in your logs that I have in mine. Like `onCreate() Meshenger version 4.1.1`. Otherwise it is not on the level of data that is needed.

**Comment by mwarning** [comment]
Thanks, But there is no debug output at all. Have install meshenger via `meshenger-4.1.1_debug.apk` file? And how did you got to the logs (so I can try as well). Maybe you need to enable the "Development options" for the phone as well?

**Comment by mwarning** [comment]
I tested with `meshenger-4.1.1_debug.apk` and have the same problem as you. Android-studio shows me the debug output, but `adb logcat` does not. No idea why that happening.

**Comment by mwarning** [comment]
Thank you for trying. The only option for you yould be to install android-studio.
